# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resource_rc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 422)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 411, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filename = QtWidgets.QLineEdit(self.groupBox)
        self.filename.setObjectName("filename")
        self.horizontalLayout.addWidget(self.filename)
        self.browse = QtWidgets.QPushButton(self.groupBox)
        self.browse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/browse-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        print(icon)
        # self.browse.setIcon(QtGui.QIcon(":/icons/browse-svgrepo-com.svg"))
        self.browse.setIcon(icon)
        self.browse.setObjectName("browse")
        self.horizontalLayout.addWidget(self.browse)
        self.verticalLayout.addWidget(self.groupBox)
        self.statusReadingFile = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.statusReadingFile.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusReadingFile.sizePolicy().hasHeightForWidth())
        self.statusReadingFile.setSizePolicy(sizePolicy)
        self.statusReadingFile.setMinimumSize(QtCore.QSize(0, 20))
        self.statusReadingFile.setMaximumSize(QtCore.QSize(16777214, 20))
        self.statusReadingFile.setAcceptDrops(False)
        self.statusReadingFile.setLineWidth(1)
        self.statusReadingFile.setText("")
        self.statusReadingFile.setObjectName("statusReadingFile")
        self.verticalLayout.addWidget(self.statusReadingFile)
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 250))
        self.graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphicsView.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.delBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delBtn.setMouseTracking(False)
        self.delBtn.setTabletTracking(False)
        self.delBtn.setAutoFillBackground(False)
        self.delBtn.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/remove-circle-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delBtn.setIcon(icon1)
        self.delBtn.setCheckable(False)
        self.delBtn.setObjectName("delBtn")
        self.horizontalLayout_2.addWidget(self.delBtn)
        self.saveBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.saveBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/save-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBtn.setIcon(icon2)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_2.addWidget(self.saveBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.browse.setText(_translate("Form", "Обзор"))
        self.delBtn.setText(_translate("Form", "Удалить выбранное"))
        self.saveBtn.setText(_translate("Form", "Сохранить"))

